name: CI & CD
on:
    push:
        branches:
            - master
jobs:
    Build-and-Publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 10

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: pnpm

            - name: Install Dependencies
              run: pnpm i --frozen-lockfile

            - name: Generate files
              run: pnpm generate

            - name: Deploy for Global
              uses: peaceiris/actions-gh-pages@v4
              with:
                  publish_dir: ./public
                  personal_token: ${{ secrets.GITHUB_TOKEN }}
                  force_orphan: true
                  cname: polyfill.web-cell.dev
