name: CI & CD
on:
    push:
        branches:
            - master
jobs:
    Build-and-Publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: yarn
            - name: Install packages
              run: yarn
            - name: Generate files
              run: |
                  yarn generate
                  cat > public/index.html <<EOF
                      <meta http-equiv="refresh" content="1;url=https://github.com/${{ github.repository }}">
                  EOF
            - name: Update document
              uses: peaceiris/actions-gh-pages@v3
              with:
                  publish_dir: ./public
                  personal_token: ${{ secrets.GITHUB_TOKEN }}
                  force_orphan: true
                  cname: polyfill.web-cell.dev
